services:
  - type: web
    name: bpay-backend
    env: python
    buildCommand: "cd fintech_project && pip install -r ../requirements.txt"
    startCommand: "cd fintech_project && python manage.py migrate && gunicorn fintech_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: FRONTEND_URL
        value: "https://transcendent-torte-870949.netlify.app"